### ISSUE TITLE
Overheal Cross

### ISSUE THREAD

**Issue by goreston** [flatlinee/omphudedit#1]
Hey man, loving your work on updating this amazing HUD. One thing I do miss is the cross that appears around your HP when you're overhealed. Is there any way to get this back?

**Comment by flatlinee** [comment]
no

**Comment by flatlinee** [comment]
and there probably won't be in the future

**Comment by flatlinee** [comment]
because it's a stylistic choice I don't enjoy and I'd like to keep the public repo as close to my version as possible to avoid inevitable conflicts and missed commits due to my version being different

**Comment by goreston** [comment]
Fair enough. I appreciate the response. I'm sure I'll get used to it not being there
