### ISSUE TITLE
Lag when dealing damage

### ISSUE THREAD

**Issue by goreston** [flatlinee/omphudedit#6]
Since the new update hit, I've been experiencing lag whenever I deal damage. It's unnoticeable for classes like solly, but with pyro and heavy the game becomes unplayable. It's probably something to do with damage numbers. I tried turning hitsounds off, and that made no difference, but uninstalling the HUD fixed the problem. Anyone else having this?

**Comment by flatlinee** [comment]
Not happening on my end...do you use damage batching?

**Comment by goreston** [comment]
I do use damage batching. I'll play around with that and get back to you.

**Comment by goreston** [comment]
OK, so, the problem occurs with or without damage batching, and with or without damage numbers.
The only time it doesn't occur is when damaging a cloaked spy. Thanks for your time!

**Comment by sigsegv-mvm** [comment]
I've dug into this. It is a custom HUD problem. Tons of info here:

https://www.reddit.com/r/tf2/comments/57760o/cause_and_fix_for_serious_fpsdrop_issue_involving/

**Comment by goreston** [comment]
This fixed it for me. Great work as always, Sigsegv. If valve put as much time into going through their code as you do, the game would be in a much better state,
